### ISSUE TITLE
CI: redesign CI-related workflows `on` key to allow marking them as "Require status checks to pass"

### ISSUE THREAD

**Issue by marcalexiei** [tuono-labs/tuono#336]
Following the merging of #304 typescript CI was failing.

## Required Status checks
To avoid this kind of problem we should mark CI workflows as required (like `pr-title-checker.yml`).
As a result,  we won't be able to merge a PR if at least one workflow didn't succeed.

In order to achieve this we should remove the `paths` filter
https://github.com/tuono-labs/tuono/blob/64220f2e27cea5c8891f571bf2b5bfacefd56afa/.github/workflows/typescript.yml#L3-L21
in the required workflows so they will be always triggered on `push` and `pull_request` events.

### Required workflows:

- `typescript-ci.yml`
- `rust-ci.yml`
- `repo-root-ci.yml`

`documentation-ci.yml` will stay as it, so it will be triggered only on related documentation changes.

## Add "CI-OK" job inside each workflow.

Each required workflow will have a "ci-ok" job which will have the following results:
- success when all other jobs are successful 
- fail when at least one of the other jobs is failed or cancelled

Example snippet:

```yml
ci-ok:
  name: CI OK
  runs-on: ubuntu-latest
  if: always()
  needs: [test, check]
  env:
    FAILURE: ${{ contains(join(needs.*.result, ','), 'failure') }}
    CANCELLED: ${{ contains(join(needs.*.result, ','), 'cancelled') }}
  steps:
    - name: Check for failure or cancelled jobs result
      shell: bash
      run: |
        echo "Failure: $FAILURE - Cancelled: $CANCELLED"
        if [ "$FAILURE" = "false" ] && [ "$CANCELLED" = "false" ]; then
          exit 0
        else
          exit 1
        fi
```

### Why doing something like this?

The "ci-ok" job of each workflows can be matched from [`main` branch ruleset](https://github.com/tuono-labs/tuono/rules/930559?ref=refs%2Fheads%2Fmain) inside the "Require status checks to pass".

By doing this can we add / edit / delete jobs inside each required workflow
without the need to update the "Require status checks to pass" list.
As a side effect this will also reduce the amount of entries to the branch ruleset making it more easy to maintain.

---

> [!TIP]
> This will come in handy when this issue will be completed and their test will be added to the CI workflows
> - #253
> - #203

---

WDYT?
