### ISSUE TITLE
Turn the `tuono_lib` crate into `tuono` for the new projects

### ISSUE THREAD

**Issue by Valerioageno** [tuono-labs/tuono#421]
## Context
It is very weird to use `tuono` on the frontend and `tuono_lib` on the backend.

## Goal
All new `tuono` projects will add the dependency using `tuono` and not `tuono_lib`

```rs
// api/health_check.rs
use tuono::Request;
use tuono::axum::http::StatusCode;

#[tuono::api(GET)]
pub async fn health_check(_req: Request) -> StatusCode {
    StatusCode::OK
}
```

## Work breakdown

With this feature, we:
- Update the dependency in each example to 
```toml
[dependencies]
tuono = { package = "tuono_lib", path = "../../crates/tuono_lib/" }
```
- Replace each `tuono_lib` occurrences in the examples with `tuono`
- Update the `tuono` CLI to correctly replace the right strings (add tests)
- Update `tuono_lib_macros` to correctly inject the `tuono` dependency
- Update the documentation
